### PR TITLE
The SQLite cache based on your version 4

### PR DESCRIPTION
**Pull request by gumblex**
This branch merged recently updated upstream code, and improved your SQLite based cache.

I use a custom class `SQLiteCacheDict` as a dict object, which is compatible with dict `FREQ` so that functions in the main module don't need to be changed. Functions `get_DAG` and `add_word` are overriden to speed up.

The `get_DAG` is roughly two times faster than v4. It may contain bugs, so please test it before using.

### CODE REVIEW

**Comment by mraygalaxy** [comment]
Did you merge into the wrong direction? Should instead I rebase against your branch?

**Comment by gumblex** [comment]
I merged the Python 3 branch (jieba3k) into master (and made it Python 2/3 compatible) in fxsjy's original repository, so it seems a bit messy. I think I merged correctly.

**Comment by mraygalaxy** [comment]
But I'm not a maintainer ------ shouldn't you merge directly to fxsjy's repository, not to mine? =)

**Comment by gumblex** [comment]
I think it's more suitable to merge to yours because this feature's "maintainer" is you. :)

**Comment by mraygalaxy** [comment]
OK, no problem. =)

Should I submit a new pull request back to master again? Or give some time for testing?

**Pull request merged**
